### ISSUE TITLE
希望支持导出插件描述

### ISSUE THREAD

**Issue by BCS1037** [Benature/obsidian-share-my-plugin-list#11]
现在已经支持导出名称、作者和版本了

![](https://github.com/Benature/obsidian-share-my-plugin-list/assets/120721474/545dac72-ae6c-4f02-b9fd-70eb0f0f4711)

希望能够将插件描述一并导出，如下图所示

![插件描述](https://github.com/Benature/obsidian-share-my-plugin-list/assets/120721474/d9a5b47c-1216-4749-bd78-60a8966e34e6)

**Comment by Benature** [comment]
The plugin now supports output description. The max length of the description in the table can be configured in the settings.
