### ISSUE TITLE
Directly export a note for sharing?

### ISSUE THREAD

**Issue by kit-zeason** [Benature/obsidian-share-my-plugin-list#2]
First thank you for your interesting plugin.

In my case, I would like to export my plugin list/table into a markdown file directly, so that I can seamlessly share it with my friends. 

Here, creating a note summative list/table would present a more viable and efficient alternative. We can conveniently execute this command using the Commander plugin, making it easily accessible from any location.

SIncerely lookiong for this function.

**Comment by Benature** [comment]
Thank you for your suggestion, this feature is planned in my mind but I haven't implemented it yet. 😂

Here's my idea: There will be one more command (say, "export to file"), and the file path and format (list/table) can be configured in the plugin's settings.

**Comment by kit-zeason** [comment]
> Thank you for your suggestion, this feature is planned in my mind but I haven't implemented it yet. 😂
> 
> Here's my idea: There will be one more command (say, "export to file"), and the file path and format (list/table) can be configured in the plugin's settings.

Yeah, that's exactly what I imagine 😎

**Comment by Benature** [comment]
Hi @kit-zeason , I would like to invite you to test the beta version of this feature. 

You can 
- First install [BRAT Plugin](https://obsidian.md/plugins?id=obsidian42-brat):
- In BRAT Plugin, click Add Beta plugin
- Enter `https://github.com/Benature/obsidian-share-my-plugin-list`
- Enable Share My Plugin List in Community plugins

if you cannot find the new command, please try to uninstall the plugin and reinstall it by BRAT

![image](https://github.com/Benature/obsidian-share-my-plugin-list/assets/35028647/40444367-54ff-4bb1-97c5-02ab566eeb2e)
