### ISSUE TITLE
Feature Request - List of disabled plugins

### ISSUE THREAD

**Issue by swini16** [Benature/obsidian-share-my-plugin-list#3]
Great work on the plugin, thanks a lot.

Was wondering if there's a way to get it so it exports a list of inactive plugins ? COuld be a separate list, or else combined with active (just with property differentiating them), or both

THanks for your time

**Comment by Benature** [comment]
v0.2.0 supports this feature, please have a try!

If the feature does not work as expected, feel free to re-open this issue. :)
