### ISSUE TITLE
Question: How to save the file in a different path by using an other filename?

### ISSUE THREAD

**Issue by merlinuwe** [Benature/obsidian-share-my-plugin-list#4]
Thanks for your great plugin.

How can I save the file in an other folder with an other name? (I work with 2 PC with different plugins.) I tried 

`Meta/Allgemeines/ShareMyPlugin_Uwe-PC-SSD.md`

but the file doesn't get created. When the file already exists, it doesn't get filled with the informations.

**Comment by Benature** [comment]
Hi, when the plugin did not work as expected, is there any log in the console?

**Comment by merlinuwe** [comment]
No, there is no log entry.

**Comment by Benature** [comment]
> But I found the problem: you have to start the plugin manually to get a result. I was expecting it to update automatically after launching Obsidian. Maybe you can add a switch that lets the user decide whether or not the output should automatically update each time Obsidian is started.

yeah, I just implemented it 🤣 #8

**Comment by Benature** [comment]
v0.2.0 supports this feature, please have a try!

If the feature does not work as expected, feel free to re-open this issue. :)
